'use client';

import React, { useState } from 'react';

interface ModalNuevaTiendaProps {
  show: boolean;
  onClose: () => void;
  onSuccess: (nuevaTienda: any) => void;
}

export default function ModalNuevaTienda({
  show,
  onClose,
  onSuccess,
}: ModalNuevaTiendaProps) {
  const [nombre, setNombre] = useState('');
  const [slug, setSlug] = useState('');
  const [direccion, setDireccion] = useState('');
  const [telefono, setTelefono] = useState('');
  const [cargando, setCargando] = useState(false);
  const [error, setError] = useState('');

  if (!show) return null;

  const handleNombreChange = (val: string) => {
    setNombre(val);
    const autogenerated = val
      .toLowerCase()
      .trim()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '');
    setSlug(autogenerated);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!nombre.trim()) {
      setError('El nombre del restaurante o sucursal es obligatorio.');
      return;
    }

    try {
      setCargando(true);
      setError('');

      const res = await fetch('/api/tiendas', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          nombre: nombre.trim(),
          slug: slug.trim(),
          direccion: direccion.trim() || undefined,
          telefono: telefono.trim() || undefined,
        }),
      });

      const data = await res.json();
      setCargando(false);

      if (data.success && data.tienda) {
        onSuccess(data.tienda);
        setNombre('');
        setSlug('');
        setDireccion('');
        setTelefono('');
        onClose();
      } else {
        setError(data.message || 'Error al crear la tienda.');
      }
    } catch (err: any) {
      setCargando(false);
      setError('Error de conexión al servidor: ' + err.message);
    }
  };

  return (
    <div
      className="modal fade show d-block"
      tabIndex={-1}
      style={{ backgroundColor: 'rgba(15, 23, 42, 0.75)', zIndex: 1060 }}
    >
      <div className="modal-dialog modal-dialog-centered">
        <div className="modal-content shadow-lg border-0 rounded-4">
          <div className="modal-header bg-primary text-white border-0 rounded-top-4 py-3">
            <h5 className="modal-title fw-bold d-flex align-items-center gap-2">
              <i className="bi bi-shop-window fs-4"></i>
              Nueva Tienda / Restaurante
            </h5>
            <button
              type="button"
              className="btn-close btn-close-white"
              onClick={onClose}
              disabled={cargando}
            ></button>
          </div>

          <form onSubmit={handleSubmit}>
            <div className="modal-body p-4">
              <div className="alert alert-info py-2 px-3 small border-0 d-flex align-items-start gap-2 mb-3">
                <i className="bi bi-info-circle-fill text-primary mt-1"></i>
                <div>
                  <strong>Plantilla Base Automatizada:</strong> La nueva tienda se creará
                  con la estructura estándar completa (Catálogo de sanciones, tolerancias,
                  multiplicador de break, uso de celular, sanciones especiales y ciclo activo) con
                  datos 100% aislados e independientes.
                </div>
              </div>

              {error && (
                <div className="alert alert-danger py-2 px-3 small border mb-3">
                  <i className="bi bi-exclamation-triangle-fill me-1"></i> {error}
                </div>
              )}

              <div className="mb-3">
                <label className="form-label small fw-semibold text-secondary">
                  Nombre Comercial del Restaurante / Tienda *
                </label>
                <div className="input-group">
                  <span className="input-group-text bg-light">
                    <i className="bi bi-building text-secondary"></i>
                  </span>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Ej. Sede San Isidro"
                    value={nombre}
                    onChange={(e) => handleNombreChange(e.target.value)}
                    required
                    autoFocus
                  />
                </div>
              </div>

              <div className="mb-3">
                <label className="form-label small fw-semibold text-secondary">
                  Identificador URL / Slug
                </label>
                <div className="input-group">
                  <span className="input-group-text bg-light small text-muted">@</span>
                  <input
                    type="text"
                    className="form-control font-monospace small"
                    placeholder="sede-san-isidro"
                    value={slug}
                    onChange={(e) => setSlug(e.target.value)}
                    required
                  />
                </div>
              </div>

              <div className="mb-3">
                <label className="form-label small fw-semibold text-secondary">
                  Dirección o Ubicación (Opcional)
                </label>
                <div className="input-group">
                  <span className="input-group-text bg-light">
                    <i className="bi bi-geo-alt text-secondary"></i>
                  </span>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Ej. Av. Conquistadores 450"
                    value={direccion}
                    onChange={(e) => setDireccion(e.target.value)}
                  />
                </div>
              </div>

              <div className="mb-2">
                <label className="form-label small fw-semibold text-secondary">
                  Teléfono de Contacto (Opcional)
                </label>
                <div className="input-group">
                  <span className="input-group-text bg-light">
                    <i className="bi bi-telephone text-secondary"></i>
                  </span>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Ej. +51 987 654 321"
                    value={telefono}
                    onChange={(e) => setTelefono(e.target.value)}
                  />
                </div>
              </div>
            </div>

            <div className="modal-footer bg-light border-0 rounded-bottom-4 px-4 py-3">
              <button
                type="button"
                className="btn btn-secondary px-3"
                onClick={onClose}
                disabled={cargando}
              >
                Cancelar
              </button>
              <button
                type="submit"
                className="btn btn-primary px-4 fw-semibold shadow-sm"
                disabled={cargando}
              >
                {cargando ? (
                  <>
                    <span className="spinner-border spinner-border-sm me-2" role="status"></span>
                    Clonando e Inicializando...
                  </>
                ) : (
                  <>
                    <i className="bi bi-plus-circle me-1"></i> Crear e Inicializar Tienda
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
